### ISSUE TITLE
Integrate configuration management into NPM environment

### ISSUE THREAD

**Issue by andrewyager** [realworldtech/radius_restserver#23]
We need to be able to swap between dev IPs and production URLs for the endpoints in the frontend application in a relatively meaningful way.

**Comment by andrewyager** [comment]
grunt-ng-constant looks like it might be a good candidate for this (e.g. http://mindthecode.com/how-to-use-environment-variables-in-your-angular-application/)

**Comment by DanielGabris** [comment]
@andrewyager I have fixed it for your comment.

**Comment by andrewyager** [comment]
Closed with pr/28 following merge and updates to grunt.js
